source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 1.2'
pod 'SwiftyJSON', '~> 2.2.0'
pod 'SwiftDate'
pod 'BRYXBanner'
pod 'SnapKit', '~> 0.12.0'
pod 'DLRadioButton'